"""0002_upd_bets_table

Revision ID: 3565399f9ca0
Revises: f8e148afc134
Create Date: 2025-02-12 16:01:50.667457

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3565399f9ca0"
down_revision: str | None = "f8e148afc134"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
